### ISSUE TITLE
対戦履歴フロント側リファクタリング

### ISSUE THREAD

**Issue by shottt** [sokorahen-szk/warzone-aoe#71]
以下の残件対応
- プレイヤー詳細ページ対戦履歴のキャッシュ処理がうまくいっていない
→このページだけ、都度読み込み。動作としては問題ないが、どこかで他ページと同じでキャッシュにしたい。
- vuex内のリファクタリング
→mutation内で共通の処理があるが、vuex内の共通処理はどこで管理するのか分からない。動作には問題ないが、どこかで共通処理の切り出しをしたい。

**Comment by sokorahen-szk** [comment]
クローズ
